package gen

//Code generated by mulgen. DO NOT EDIT (i mean, it will all be lost in the void)

import (
	"context"
	"github.com/Vliro/mulbase"
	"time"
)

var _ context.Context
var _ time.Time
var _ mulbase.Fields
