package gen

//Code generated by mulgen. DO NOT EDIT (i mean, it will all be lost in the void)

import (
	"context"
	"github.com/Vliro/humus"
	"time"
)

var _ context.Context
var _ time.Time
var _ humus.Fields

//Beginning of field.template. General functions.
var globalFields = make(map[humus.Predicate]humus.Field)

func GetField(name humus.Predicate) humus.Field {
	return globalFields[name]
}

func MakeField(name humus.Predicate, flags humus.FieldMeta) humus.Field {
	var fi = humus.Field{Name: name, Meta: flags}
	globalFields[name] = fi
	return fi
}

func GetGlobalFields() map[humus.Predicate]humus.Field {
	return globalFields
}

type queryError struct {
	Msg string
}

func (q queryError) Error() string {
	return q.Msg
}

func newError(msg string) error {
	return queryError{msg}
}
