package gen

//Code generated by mulgen. DO NOT EDIT (i mean, it will all be lost in the void)

import (
	"context"
	"github.com/Vliro/mulbase"
	"time"
)

var _ context.Context
var _ time.Time
var _ mulbase.Fields

//Beginning of field.template. General functions.
var globalFields = make(map[mulbase.Predicate]mulbase.Field)

func GetField(name mulbase.Predicate) mulbase.Field {
	return globalFields[name]
}

func MakeField(name mulbase.Predicate, flags mulbase.FieldMeta) mulbase.Field {
	var fi = mulbase.Field{Name: name, Meta: flags}
	globalFields[name] = fi
	return fi
}

func GetGlobalFields() map[mulbase.Predicate]mulbase.Field {
	return globalFields
}

type queryError struct {
	Msg string
}

func (q queryError) Error() string {
	return q.Msg
}

func newError(msg string) error {
	return queryError{msg}
}
