package gen

// Code generated by gen. DO NOT EDIT (or feel free but it will be lost!).
import (
	"github.com/Vliro/mulbase"
)

var QuestionMetaFields mulbase.FieldList = []mulbase.Field{MakeField("Question.id", 0), MakeField("Post.datePublished", 0)}
var QuestionTestFields mulbase.FieldList = []mulbase.Field{MakeField("Post.datePublished", 0)}
