package gen 
// Code generated by gen. DO NOT EDIT (or feel free but it will be lost!).
import ( 
"github.com/Vliro/mulbase"
)
var UserMetaFields mulbase.FieldList = []mulbase.Field{MakeField("User.name", 0),MakeField("User.rank", 0)} 
