package gen

//Code generated by mulgen. DO NOT EDIT (i mean, it will all be lost in the void)

import (
	"context"
	"github.com/Vliro/humus"
	"time"
)

var _ context.Context
var _ time.Time
var _ humus.Fields

//Created from a GraphQL interface.
type Post struct {
	//This line declares basic properties for a database node.
	humus.Node
	Text          string     `json:"Post.text,omitempty"`
	DatePublished *time.Time `json:"Post.datePublished,omitempty"`
}

var PostFields humus.FieldList = []humus.Field{MakeField("Post.text", 0), MakeField("Post.datePublished", 0)}

//Generating constant field values.
const (
	PostTextField          humus.Predicate = "Post.text"
	PostDatePublishedField humus.Predicate = "Post.datePublished"
)

//SaveValues saves the node values that
//do not contain any references to other objects.
func (r *Post) SaveValues(ctx context.Context, txn *humus.Txn) error {
	mut := humus.CreateMutation(r.Values(), humus.MutateSet)
	_, err := txn.Mutate(ctx, mut)
	return err
}
func (r *Post) GetType() []string {
	if r.Type == nil {
		r.SetType()
	}
	return r.Type
}

//Reset resets the node to only its UID
//component. Useful for saving to the database.
//Calling this function ensures that, at most,
//the uid and type is serialized.
func (r *Post) Reset() {
	if r != nil {
		*r = Post{Node: r.Node}
	}
}

func (r *Post) Facets() []string {
	return nil
}

//Fields returns all Scalar fields for this value.
func (r *Post) Fields() humus.FieldList {
	return PostFields
}

//Sets the types. This DOES NOT include interfaces!
//as they are set in dgraph already.
func (r *Post) SetType() {
	r.Type = []string{
		"Post",
	}
}

//Values returns all the scalar values for this node.
func (r *Post) Values() humus.DNode {
	var m PostScalars
	m.Text = r.Text
	m.DatePublished = r.DatePublished
	r.SetType()
	m.Node = r.Node
	return &m
}

//Values returns all the scalar values for this node.
//Note that this completely ignores any omitempty tags so use with care.
func (r *Post) MapValues() humus.Mapper {
	var m = make(map[string]interface{})
	m["Post.text"] = r.Text
	m["Post.datePublished"] = r.DatePublished
	if r.Uid != "" {
		m["uid"] = r.Uid
	}
	r.SetType()
	m["dgraph.type"] = r.Type
	return m
}

//PostScalars is simply to avoid a map[string]interface{}
//It is a mirror of the previous struct with all scalar values.
type PostScalars struct {
	humus.Node
	Text          string     `json:"Post.text,omitempty"`
	DatePublished *time.Time `json:"Post.datePublished,omitempty"`
}

func (s *PostScalars) Values() humus.DNode {
	return s
}

func (s *PostScalars) MapValues() humus.Mapper {
	panic("PostScalars called, use the original one instead")
}

func (s *PostScalars) Fields() humus.FieldList {
	return PostFields
}

//End of model.template
type Question struct {
	//This line declares basic properties for a database node.
	humus.Node
	//List of interfaces implemented.
	Post
	//Regular fields
	Title string `json:"Question.title,omitempty"`
	Id    int    `json:"Question.id,omitempty"`
}

var QuestionFields humus.FieldList = []humus.Field{MakeField("Question.title", 0), MakeField("Question.id", 0), MakeField("Post.text", 0), MakeField("Post.datePublished", 0)}

//Generating constant field values.
const (
	QuestionTitleField         humus.Predicate = "Question.title"
	QuestionIdField            humus.Predicate = "Question.id"
	QuestionTextField          humus.Predicate = "Post.text"
	QuestionDatePublishedField humus.Predicate = "Post.datePublished"
)

//SaveValues saves the node values that
//do not contain any references to other objects.
func (r *Question) SaveValues(ctx context.Context, txn *humus.Txn) error {
	mut := humus.CreateMutation(r.Values(), humus.MutateSet)
	_, err := txn.Mutate(ctx, mut)
	return err
}
func (r *Question) GetType() []string {
	if r.Type == nil {
		r.SetType()
	}
	return r.Type
}

//Reset resets the node to only its UID
//component. Useful for saving to the database.
//Calling this function ensures that, at most,
//the uid and type is serialized.
func (r *Question) Reset() {
	if r != nil {
		*r = Question{Node: r.Node}
	}
}

func (r *Question) Facets() []string {
	return nil
}

//Fields returns all Scalar fields for this value.
func (r *Question) Fields() humus.FieldList {
	return QuestionFields
}

//Sets the types. This DOES NOT include interfaces!
//as they are set in dgraph already.
func (r *Question) SetType() {
	r.Type = []string{
		"Question",
	}
}

//Values returns all the scalar values for this node.
func (r *Question) Values() humus.DNode {
	var m QuestionScalars
	m.Title = r.Title
	m.Id = r.Id
	m.Text = r.Text
	m.DatePublished = r.DatePublished
	r.SetType()
	m.Node = r.Node
	return &m
}

//Values returns all the scalar values for this node.
//Note that this completely ignores any omitempty tags so use with care.
func (r *Question) MapValues() humus.Mapper {
	var m = make(map[string]interface{})
	m["Question.title"] = r.Title
	m["Question.id"] = r.Id
	m["Post.text"] = r.Text
	m["Post.datePublished"] = r.DatePublished
	if r.Uid != "" {
		m["uid"] = r.Uid
	}
	r.SetType()
	m["dgraph.type"] = r.Type
	return m
}

//QuestionScalars is simply to avoid a map[string]interface{}
//It is a mirror of the previous struct with all scalar values.
type QuestionScalars struct {
	humus.Node
	Title         string     `json:"Question.title,omitempty"`
	Id            int        `json:"Question.id,omitempty"`
	Text          string     `json:"Post.text,omitempty"`
	DatePublished *time.Time `json:"Post.datePublished,omitempty"`
}

func (s *QuestionScalars) Values() humus.DNode {
	return s
}

func (s *QuestionScalars) MapValues() humus.Mapper {
	panic("QuestionScalars called, use the original one instead")
}

func (s *QuestionScalars) Fields() humus.FieldList {
	return QuestionFields
}

//End of model.template
type Comment struct {
	//This line declares basic properties for a database node.
	humus.Node
	//List of interfaces implemented.
	Post
	//Regular fields
	Episode Type `json:"Comment.episode,omitempty"`
}

var CommentFields humus.FieldList = []humus.Field{MakeField("Comment.episode", 0), MakeField("Post.text", 0), MakeField("Post.datePublished", 0)}

//Generating constant field values.
const (
	CommentEpisodeField       humus.Predicate = "Comment.episode"
	CommentTextField          humus.Predicate = "Post.text"
	CommentDatePublishedField humus.Predicate = "Post.datePublished"
)

//SaveValues saves the node values that
//do not contain any references to other objects.
func (r *Comment) SaveValues(ctx context.Context, txn *humus.Txn) error {
	mut := humus.CreateMutation(r.Values(), humus.MutateSet)
	_, err := txn.Mutate(ctx, mut)
	return err
}
func (r *Comment) GetType() []string {
	if r.Type == nil {
		r.SetType()
	}
	return r.Type
}

//Reset resets the node to only its UID
//component. Useful for saving to the database.
//Calling this function ensures that, at most,
//the uid and type is serialized.
func (r *Comment) Reset() {
	if r != nil {
		*r = Comment{Node: r.Node}
	}
}

func (r *Comment) Facets() []string {
	return nil
}

//Fields returns all Scalar fields for this value.
func (r *Comment) Fields() humus.FieldList {
	return CommentFields
}

//Sets the types. This DOES NOT include interfaces!
//as they are set in dgraph already.
func (r *Comment) SetType() {
	r.Type = []string{
		"Comment",
	}
}

//Values returns all the scalar values for this node.
func (r *Comment) Values() humus.DNode {
	var m CommentScalars
	m.Episode = r.Episode
	m.Text = r.Text
	m.DatePublished = r.DatePublished
	r.SetType()
	m.Node = r.Node
	return &m
}

//Values returns all the scalar values for this node.
//Note that this completely ignores any omitempty tags so use with care.
func (r *Comment) MapValues() humus.Mapper {
	var m = make(map[string]interface{})
	m["Comment.episode"] = r.Episode
	m["Post.text"] = r.Text
	m["Post.datePublished"] = r.DatePublished
	if r.Uid != "" {
		m["uid"] = r.Uid
	}
	r.SetType()
	m["dgraph.type"] = r.Type
	return m
}

//CommentScalars is simply to avoid a map[string]interface{}
//It is a mirror of the previous struct with all scalar values.
type CommentScalars struct {
	humus.Node
	Episode       Type       `json:"Comment.episode,omitempty"`
	Text          string     `json:"Post.text,omitempty"`
	DatePublished *time.Time `json:"Post.datePublished,omitempty"`
}

func (s *CommentScalars) Values() humus.DNode {
	return s
}

func (s *CommentScalars) MapValues() humus.Mapper {
	panic("CommentScalars called, use the original one instead")
}

func (s *CommentScalars) Fields() humus.FieldList {
	return CommentFields
}

//End of model.template
type Error struct {
	//This line declares basic properties for a database node.
	humus.Node
	//Regular fields
	Message   string     `json:"Error.message,omitempty"`
	ErrorType string     `json:"Error.errorType,omitempty"`
	Time      *time.Time `json:"Error.time,omitempty"`
}

var ErrorFields humus.FieldList = []humus.Field{MakeField("Error.message", 0), MakeField("Error.errorType", 0), MakeField("Error.time", 0)}

//Generating constant field values.
const (
	ErrorMessageField   humus.Predicate = "Error.message"
	ErrorErrorTypeField humus.Predicate = "Error.errorType"
	ErrorTimeField      humus.Predicate = "Error.time"
)

//SaveValues saves the node values that
//do not contain any references to other objects.
func (r *Error) SaveValues(ctx context.Context, txn *humus.Txn) error {
	mut := humus.CreateMutation(r.Values(), humus.MutateSet)
	_, err := txn.Mutate(ctx, mut)
	return err
}
func (r *Error) GetType() []string {
	if r.Type == nil {
		r.SetType()
	}
	return r.Type
}

//Reset resets the node to only its UID
//component. Useful for saving to the database.
//Calling this function ensures that, at most,
//the uid and type is serialized.
func (r *Error) Reset() {
	if r != nil {
		*r = Error{Node: r.Node}
	}
}

func (r *Error) Facets() []string {
	return nil
}

//Fields returns all Scalar fields for this value.
func (r *Error) Fields() humus.FieldList {
	return ErrorFields
}

//Sets the types. This DOES NOT include interfaces!
//as they are set in dgraph already.
func (r *Error) SetType() {
	r.Type = []string{
		"Error",
	}
}

//Values returns all the scalar values for this node.
func (r *Error) Values() humus.DNode {
	var m ErrorScalars
	m.Message = r.Message
	m.ErrorType = r.ErrorType
	m.Time = r.Time
	r.SetType()
	m.Node = r.Node
	return &m
}

//Values returns all the scalar values for this node.
//Note that this completely ignores any omitempty tags so use with care.
func (r *Error) MapValues() humus.Mapper {
	var m = make(map[string]interface{})
	m["Error.message"] = r.Message
	m["Error.errorType"] = r.ErrorType
	m["Error.time"] = r.Time
	if r.Uid != "" {
		m["uid"] = r.Uid
	}
	r.SetType()
	m["dgraph.type"] = r.Type
	return m
}

//ErrorScalars is simply to avoid a map[string]interface{}
//It is a mirror of the previous struct with all scalar values.
type ErrorScalars struct {
	humus.Node
	Message   string     `json:"Error.message,omitempty"`
	ErrorType string     `json:"Error.errorType,omitempty"`
	Time      *time.Time `json:"Error.time,omitempty"`
}

func (s *ErrorScalars) Values() humus.DNode {
	return s
}

func (s *ErrorScalars) MapValues() humus.Mapper {
	panic("ErrorScalars called, use the original one instead")
}

func (s *ErrorScalars) Fields() humus.FieldList {
	return ErrorFields
}

//End of model.template
